"""Emit include/stub_capture_jpeg.h from a tiny gradient JPEG."""
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("PIL not installed; pip install Pillow")
    raise

root = Path(__file__).resolve().parents[1]
out_h = root / "include" / "stub_capture_jpeg.h"
im = Image.new("RGB", (280, 210))
px = im.load()
for y in range(210):
    for x in range(280):
        px[x, y] = (min(255, x * 2), min(255, y + 40), min(255, (x + y) // 2))
jpg_path = root / "tools" / "_stub_preview.jpg"
im.save(jpg_path, "JPEG", quality=82)
raw = jpg_path.read_bytes()
lines = [f"// Auto-generated by tools/gen_stub_jpeg.py ({len(raw)} bytes)\n",
         "#pragma once\n", "#include <Arduino.h>\n\n",
         f"#define STUB_CAPTURE_JPEG_LEN ({len(raw)})\n\n",
         "static const uint8_t STUB_CAPTURE_JPEG[] PROGMEM = {\n"]
row = "  "
for i, b in enumerate(raw):
    row += f"0x{b:02X},"
    if (i + 1) % 16 == 0:
        lines.append(row + "\n")
        row = "  "
    else:
        row += " "
if row.strip():
    lines.append(row.rstrip() + "\n")
lines.append("};\n")
out_h.write_text("".join(lines), encoding="utf-8")
print(f"Wrote {out_h} ({len(raw)} bytes)")
