"""
Generate include/stub_capture_bitmap.h — a 240x240 RGB565 bitmap embedded
directly in flash. Used by the capture-ritual preview so the device can
show an ACTUAL photo-like image without going through JPEGDEC (which
crashes on our stub JPEG on ESP32-S3, and which we don't need anyway
until the SSCMA Himax camera bridge is wired in).

Run:  python tools/gen_stub_bitmap.py

Scene: a stylised sunrise over water — gradient sky, sun, horizon,
reflected water ripples. Looks like a real processed photo at 240x240.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter
import math

ROOT = Path(__file__).resolve().parents[1]
OUT_H = ROOT / "include" / "stub_capture_bitmap.h"

W, H = 240, 240

# ---------- render the "photo" ----------
img = Image.new("RGB", (W, H))
px = img.load()

# Sky gradient: top deep indigo -> mid warm orange -> horizon peach
def lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))

sky_top  = (28, 20, 64)     # deep indigo
sky_mid  = (230, 110, 60)   # warm orange
sky_low  = (255, 200, 140)  # peach / horizon glow
water_top= (90,  60, 110)   # dusky purple water
water_bot= (20,  12,  40)   # near-black water
horizon_y = 135

for y in range(H):
    if y < horizon_y:
        # sky: two-stop gradient
        t = y / horizon_y
        if t < 0.55:
            c = lerp(sky_top, sky_mid, t / 0.55)
        else:
            c = lerp(sky_mid, sky_low, (t - 0.55) / 0.45)
    else:
        # water
        t = (y - horizon_y) / (H - horizon_y)
        c = lerp(water_top, water_bot, t)
    for x in range(W):
        px[x, y] = c

# Sun — soft radial glow
cx_sun, cy_sun, r_sun = 130, 110, 28
for y in range(H):
    for x in range(W):
        dx = x - cx_sun
        dy = y - cy_sun
        d = math.hypot(dx, dy)
        if d <= r_sun:
            # solid sun core fading to edge
            t = d / r_sun
            core = (255, 240, 170)
            edge = (255, 180, 80)
            c = lerp(core, edge, t)
            px[x, y] = c
        elif d <= r_sun * 2.2:
            # halo blend
            t = (d - r_sun) / (r_sun * 1.2)
            base = px[x, y]
            halo = (255, 200, 110)
            c = lerp(halo, base, t)
            px[x, y] = c

# Horizon band — thin bright line + soft haze
for x in range(W):
    for y in range(horizon_y - 2, horizon_y + 1):
        bc = px[x, y]
        px[x, y] = lerp(bc, (255, 230, 180), 0.55)

# Sun reflection streak on water
draw = ImageDraw.Draw(img)
for y in range(horizon_y, H):
    t = (y - horizon_y) / (H - horizon_y)
    streak_half = int(8 + t * 40)
    cx_streak = cx_sun + int(math.sin(y * 0.2) * 2)
    for x in range(cx_streak - streak_half, cx_streak + streak_half):
        if 0 <= x < W:
            base = px[x, y]
            glow = (255, 200, 140)
            strength = 0.55 * (1 - t)
            px[x, y] = lerp(base, glow, max(0.0, strength))

# Distant mountain silhouette on the horizon
silhouette = [
    (0, horizon_y - 2),
    (35, horizon_y - 22),
    (68, horizon_y - 8),
    (105, horizon_y - 28),
    (140, horizon_y - 5),
    (172, horizon_y - 18),
    (205, horizon_y - 10),
    (240, horizon_y - 2),
    (240, horizon_y + 2),
    (0, horizon_y + 2),
]
draw.polygon(silhouette, fill=(18, 12, 40))

# Light noise for that "processed photo" feel
import random
random.seed(42)
for _ in range(1500):
    x = random.randint(0, W - 1)
    y = random.randint(0, H - 1)
    base = px[x, y]
    n = random.randint(-12, 12)
    px[x, y] = tuple(max(0, min(255, c + n)) for c in base)

# Slight blur for cinematic softness
img = img.filter(ImageFilter.GaussianBlur(radius=0.5))

# Save a PNG preview so humans can eyeball it
img.save(ROOT / "tools" / "_stub_preview.png")

# ---------- encode to RGB565 (little-endian, matches Arduino_Canvas) ----------
pixels_le = bytearray(W * H * 2)
px = img.load()
for y in range(H):
    for x in range(W):
        r, g, b = px[x, y]
        v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        i = (y * W + x) * 2
        pixels_le[i]     = v & 0xFF
        pixels_le[i + 1] = (v >> 8) & 0xFF

# ---------- emit C header ----------
lines = [
    f"// Auto-generated by tools/gen_stub_bitmap.py ({W}x{H} RGB565, {len(pixels_le)} bytes)\n",
    "#pragma once\n",
    "#include <Arduino.h>\n\n",
    f"#define STUB_CAPTURE_BMP_W   {W}\n",
    f"#define STUB_CAPTURE_BMP_H   {H}\n",
    f"#define STUB_CAPTURE_BMP_LEN {len(pixels_le)}\n\n",
    "// 16-bit RGB565, little-endian (Arduino_GFX RGB565_LITTLE_ENDIAN).\n",
    "static const uint16_t STUB_CAPTURE_BMP[] PROGMEM = {\n",
]
row = "  "
total_pixels = W * H
for i in range(total_pixels):
    lo = pixels_le[i * 2]
    hi = pixels_le[i * 2 + 1]
    v = (hi << 8) | lo
    row += f"0x{v:04X},"
    if (i + 1) % 12 == 0:
        lines.append(row + "\n")
        row = "  "
    else:
        row += " "
if row.strip():
    lines.append(row.rstrip() + "\n")
lines.append("};\n")
OUT_H.write_text("".join(lines), encoding="utf-8")
print(f"Wrote {OUT_H} ({len(pixels_le)} bytes, {W}x{H} RGB565)")
