#!/usr/bin/env python3
"""
img2sprite.py — Convert PNG pixel art into C RGB565 sprite arrays
for HabitTracker / Tamagotchi Habit Companion firmware.

USAGE:
    python tools/img2sprite.py <input_dir_or_file> <output_header>

EXAMPLES:
    # Convert a single PNG to a one-frame sprite
    python tools/img2sprite.py assets/sprites/thriving_0.png assets/pet_sprites.h

    # Convert an entire directory of PNGs, grouping by state name prefix
    python tools/img2sprite.py assets/sprites/ assets/pet_sprites.h

SPRITE FILE NAMING CONVENTION:
    <state>_<frame>.png  e.g. thriving_0.png, thriving_1.png, critical_3.png
    Valid state names: thriving, happy, tired, struggling, critical

IMAGE REQUIREMENTS:
    - 64×64 pixels exactly (script will warn and resize if different)
    - RGBA or RGB mode — transparent pixels are filled with black (0x0000)
    - Standard PNG, no special compression required

OUTPUT FORMAT:
    The script generates a C header file with one uint16_t array per
    animation frame, named SPRITE_<STATE>_F<frame>[]. It also generates
    the multi-frame 2D arrays that gui.cpp expects.

DEPENDENCIES:
    pip install Pillow
"""

import sys
import os
import re
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

SPRITE_W = 64
SPRITE_H = 64

# Valid state names and their order in the output file
STATES = ["thriving", "happy", "tired", "struggling", "critical"]

# LEDC channel constant names expected by gui.cpp
STATE_CONST_NAMES = {
    "thriving":   "SPRITE_THRIVING",
    "happy":      "SPRITE_HAPPY",
    "tired":      "SPRITE_TIRED",
    "struggling": "SPRITE_STRUGGLING",
    "critical":   "SPRITE_CRITICAL",
}


def rgb_to_rgb565(r: int, g: int, b: int) -> int:
    """Pack 8-bit R,G,B into a 16-bit RGB565 value (little-endian)."""
    r5 = (r >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    b5 = (b >> 3) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5


def png_to_rgb565_array(path: Path) -> list[int]:
    """Convert a PNG file to a flat list of RGB565 uint16_t values."""
    img = Image.open(path).convert("RGBA")

    if img.width != SPRITE_W or img.height != SPRITE_H:
        print(f"  WARNING: {path.name} is {img.width}x{img.height}, expected {SPRITE_W}x{SPRITE_H}. Resizing.")
        img = img.resize((SPRITE_W, SPRITE_H), Image.NEAREST)

    pixels = []
    for y in range(SPRITE_H):
        for x in range(SPRITE_W):
            r, g, b, a = img.getpixel((x, y))
            # Blend transparent pixels onto black background
            if a < 128:
                r, g, b = 0, 0, 0
            else:
                # Pre-multiply alpha for semi-transparent pixels
                r = (r * a) // 255
                g = (g * a) // 255
                b = (b * a) // 255
            pixels.append(rgb_to_rgb565(r, g, b))

    return pixels


def pixels_to_c_array(pixels: list[int], name: str) -> str:
    """Format a flat pixel list as a C uint16_t array literal."""
    lines = [f"// {len(pixels)} pixels ({SPRITE_W}x{SPRITE_H})"]
    lines.append(f"static const uint16_t {name}[{len(pixels)}] = {{")

    # 8 values per line for readability
    for i in range(0, len(pixels), 8):
        chunk = pixels[i:i+8]
        line  = "  " + ", ".join(f"0x{v:04X}" for v in chunk)
        if i + 8 < len(pixels):
            line += ","
        lines.append(line)

    lines.append("};")
    return "\n".join(lines)


def discover_frames(source_dir: Path) -> dict[str, list[Path]]:
    """
    Scan source_dir for PNG files matching <state>_<frame>.png.
    Returns {state: [sorted list of paths]}.
    """
    frames: dict[str, list[Path]] = {s: [] for s in STATES}
    pattern = re.compile(r"^(thriving|happy|tired|struggling|critical)_(\d+)\.png$",
                         re.IGNORECASE)

    for f in sorted(source_dir.glob("*.png")):
        m = pattern.match(f.name)
        if m:
            state = m.group(1).lower()
            frames[state].append(f)
        else:
            print(f"  SKIP: {f.name} (doesn't match <state>_<frame>.png)")

    # Sort frames within each state by frame number
    for state in STATES:
        frames[state].sort(key=lambda p: int(re.search(r"_(\d+)\.png$", p.name).group(1)))

    return frames


def generate_header(frames: dict[str, list[Path]], out_path: Path) -> None:
    """Write the complete C header file."""
    lines = [
        "#pragma once",
        "// =============================================================",
        "// pet_sprites.h — AUTO-GENERATED by tools/img2sprite.py",
        "// DO NOT EDIT MANUALLY — re-run the script to regenerate.",
        "// =============================================================",
        "",
        "#include <stdint.h>",
        "",
        f"#define SPRITE_WIDTH   {SPRITE_W}",
        f"#define SPRITE_HEIGHT  {SPRITE_H}",
        f"#define SPRITE_PIXELS  ({SPRITE_W} * {SPRITE_H})",
        "",
    ]

    # Frame count defines
    for state in STATES:
        count = max(len(frames[state]), 1)
        const = STATE_CONST_NAMES[state]
        lines.append(f"#define SPRITE_FRAMES_{state.upper():12s} {count}")

    lines.append("")

    # Per-state arrays
    for state in STATES:
        const = STATE_CONST_NAMES[state]
        state_frames = frames[state]

        if not state_frames:
            lines.append(f"// No PNG found for state '{state}' — using placeholder")
            # Emit a single-frame placeholder (solid mid-grey)
            placeholder = [0x8410] * (SPRITE_W * SPRITE_H)
            lines.append(pixels_to_c_array(placeholder, f"{const}_F0"))
            lines.append(f"static const uint16_t* const {const}[1] = {{ {const}_F0 }};")
            lines.append("")
            continue

        frame_names = []
        for i, png_path in enumerate(state_frames):
            frame_const = f"{const}_F{i}"
            print(f"  Converting {png_path.name} → {frame_const}[]")
            pixels = png_to_rgb565_array(png_path)
            lines.append(pixels_to_c_array(pixels, frame_const))
            lines.append("")
            frame_names.append(frame_const)

        # Build the 2D pointer array the firmware uses
        frame_ptrs = ", ".join(frame_names)
        count      = len(frame_names)
        lines.append(f"static const uint16_t* const {const}[{count}] = {{ {frame_ptrs} }};")
        lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {out_path} ({out_path.stat().st_size:,} bytes)")


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    source = Path(sys.argv[1])
    output = Path(sys.argv[2])

    # Single file mode — wrap it in the expected naming convention if possible
    if source.is_file():
        print(f"Single file mode: {source.name}")
        m = re.match(r"(thriving|happy|tired|struggling|critical)_(\d+)\.png$",
                     source.name, re.IGNORECASE)
        if not m:
            print("ERROR: Single file must be named <state>_<frame>.png")
            sys.exit(1)
        frames = {s: [] for s in STATES}
        frames[m.group(1).lower()] = [source]
        source_label = source.name
    elif source.is_dir():
        print(f"Scanning directory: {source}")
        frames = discover_frames(source)
        source_label = str(source)
    else:
        print(f"ERROR: {source} is not a file or directory")
        sys.exit(1)

    total_pngs = sum(len(v) for v in frames.values())
    print(f"Found {total_pngs} sprite PNG(s) across {len([s for s in STATES if frames[s]])} states")
    print(f"Output: {output}")
    print()

    generate_header(frames, output)

    print("\nDone! Rebuild firmware with: pio run")
    print("To use sprites instead of procedural drawing, see the comment")
    print("at the bottom of assets/pet_sprites.h for gui.cpp integration.")


if __name__ == "__main__":
    main()
